### ISSUE TITLE
[Bug] Sett standard tekstfarge på inputs

### ISSUE THREAD

**Issue by strombraaten** [varianter/variant-rocks#26]
Rapportert av @mikaelbr og @jonasbjoralt. Om jeg forstår rett så går nemlig to tilbakemeldingene der på samme bugen:

> Burde settes standard tekstfarge på inputs også 
![image](https://github.com/varianter/variant-rocks/assets/72508979/d79b220d-1971-41d1-a1d5-b62409d016b4)

> Kanskje ikke hvit tekstfarge?
![image](https://github.com/varianter/variant-rocks/assets/72508979/8f2e04b3-0b9a-4324-b109-0957310aea0b)

---

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by mikaelbr** [comment]
Korrekt

**Comment by strombraaten** [comment]
Phew! Takk og lov for at det blei oversatt 😅
